### ISSUE TITLE
link to manifest.json is throwing 404 Not Found

### ISSUE THREAD

**Issue by Eulentier161** [MartenFrehse/Naturbienen.de_Website#4]
i noticed that the link to manifest.json is throwing a `404 Not Found` but i wasnt able to find where this link is supposed to lead, so i left it untouched.

_Originally posted by @Eulentier161 in https://github.com/MartenFrehse/Naturbienen.de_Website/pull/3#issuecomment-1803945078_

**Comment by MartenFrehse** [comment]
The manifest.json file had somehow disappeared. I added it again.
